// AUTO-GENERATED by scripts/extract-floorplan-rooms.py
// Do not edit by hand — regenerate by running:
//   python3 scripts/extract-floorplan-rooms.py <image-path>
//
// Source image: public/samples/floor-plan/sample-1f-framing.png
// Image natural size: 3309 × 2339
// Detected rooms: 4

import type { DrawingHotspot } from "./drawing-quick-viewer"

export const detectedImageSize = { width: 3309, height: 2339 } as const

export const detectedHotspots: DrawingHotspot[] = [
  {
    "id": "hs-genkan",
    "roomName": "玄関",
    "aliases": [
      "エントランス",
      "ENTRANCE",
      "玄 関"
    ],
    "x": 48.17,
    "y": 25.8,
    "rect": {
      "x": 46.17,
      "y": 23.8,
      "width": 4.0,
      "height": 4.0
    },
    "notes": [
      {
        "label": "上り框",
        "value": "H=200mm (ヒノキ 集成)"
      },
      {
        "label": "玄関ドア",
        "value": "W910 × H2,200 (断熱 K1.6)"
      },
      {
        "label": "土間仕上",
        "value": "300角タイル (LIXIL アスペッタ)"
      }
    ],
    "swatch": "#10b981"
  },
  {
    "id": "hs-garage",
    "roomName": "車庫",
    "aliases": [
      "ガレージ",
      "GARAGE"
    ],
    "x": 36.43,
    "y": 27.4,
    "rect": {
      "x": 34.43,
      "y": 25.4,
      "width": 4.0,
      "height": 4.0
    },
    "notes": [
      {
        "label": "床仕上",
        "value": "金ゴテ仕上 (勾配 1/100)"
      },
      {
        "label": "土間コン厚",
        "value": "150mm (ワイヤーメッシュ φ6 @150)"
      },
      {
        "label": "開口部",
        "value": "シャッター W2,730mm × H2,200mm"
      }
    ],
    "swatch": "#a855f7"
  },
  {
    "id": "hs-storage",
    "roomName": "床下収納",
    "aliases": [
      "床下",
      "STORAGE",
      "床 下 収 納"
    ],
    "x": 47.16,
    "y": 62.76,
    "rect": {
      "x": 44.33,
      "y": 60.76,
      "width": 5.66,
      "height": 4.0
    },
    "notes": [
      {
        "label": "蓋寸法",
        "value": "610 × 610mm"
      },
      {
        "label": "床下高さ",
        "value": "445mm"
      },
      {
        "label": "本体",
        "value": "城東 ステン製 気密タイプ"
      }
    ],
    "swatch": "#d97706"
  },
  {
    "id": "hs-bath",
    "roomName": "浴室",
    "aliases": [
      "U/B",
      "UNIT BATH",
      "ユニットバス",
      "浴室",
      "AUIB"
    ],
    "x": 49.3,
    "y": 70.99,
    "rect": {
      "x": 46.67,
      "y": 68.99,
      "width": 5.27,
      "height": 4.0
    },
    "notes": [
      {
        "label": "サイズ",
        "value": "1216 (1,820 × 1,365mm)"
      },
      {
        "label": "メーカー",
        "value": "TOTO サザナ Hシリーズ"
      },
      {
        "label": "防水",
        "value": "立ち上がり H=400mm"
      }
    ],
    "swatch": "#0e7490"
  }
]
