// Hotspot coordinates and image size are AUTO-GENERATED by
// `scripts/extract-floorplan-rooms.py`. Switching the source image and
// re-running the script regenerates everything in
// `drawing-quick-viewer.detected.ts` — no hand-tuning of `rect` values.

import { detectedHotspots, detectedImageSize } from "./drawing-quick-viewer.detected"

export type DrawingHotspot = {
  id: string
  roomName: string
  aliases: string[]
  /** Center position as percentage (0-100) within the floor plan image. */
  x: number
  y: number
  /** Highlight box (rect) — also percentages. */
  rect: { x: number; y: number; width: number; height: number }
  notes: { label: string; value: string }[]
  swatch: string
}

export const sampleFloorPlan = {
  drawingTitle: "1階 床伏図",
  drawingNumber: "S-03 / Rev.1",
  scale: "1:50",
  lastUpdated: "2026-04-18",
  imagePath: "/samples/floor-plan/sample-1f-framing.png",
  imageWidth: detectedImageSize.width,
  imageHeight: detectedImageSize.height,
  detectedRoomCount: detectedHotspots.length,
  imageAttribution: {
    author: "株式会社 B-Architect (構造設計サンプル)",
    license: "出典明記の上 デモ目的で 使用",
    sourceUrl: "http://www.b-architect.co.jp/architect/sample2.pdf",
  },
}

export const sampleHotspots = detectedHotspots

export function searchHotspots(
  hotspots: DrawingHotspot[],
  query: string,
): DrawingHotspot[] {
  const q = query.trim()
  if (!q) return hotspots
  return hotspots.filter((h) => {
    if (h.roomName.includes(q)) return true
    return h.aliases.some((alias) => alias.toLowerCase().includes(q.toLowerCase()))
  })
}
